### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by OmBabosa** [ibm-messaging/mq-container#408]
Hi,

I am trying to supply TLS certificates to my MQ POD (running on test Microk8s one node cluster). i follow 'https://github.com/ibm-messaging/mq-container/blob/master/docs/usage.md#supplying-tls-certificates' to supply the TLS certificate, and i make use of secrets (that holds the required TLS certificates) as the volume (see below). 

Secret: 
kubectl create secret generic testone-secret --from-file=mqsc=./queues.mqsc --from-file=privatekey=./test1key.key --from-file=personalcert=./test1.crt --from-file=clientcert=./test2.crt --namespace dev-ns

Deployment YAML extract:
 volumeMounts:
          - name: personalcertificate
            mountPath: "/etc/mqm/pki/keys/mykey"
          - name: clientcertificate
            mountPath: "/etc/mqm/pki/trust/0"
          - name: mqsc
            mountPath: "/etc/mqm/queues.mqsc"
            subPath: queues.mqsc

volumes:
       - name: personalcertificate
         secret:
           secretName: testone-secret
           optional: true
           items:
           - key: privatekey
             path: test1key.key
           - key: personalcert
             path: test1.crt
       - name: clientcertificate
         secret:
           secretName: testone-secret
           optional: true
           items:
           - key: clientcert
             path: test2.crt
       - name: mqsc
         secret:
           secretName: testone-secret
           optional: true
           items:
           - key: mqsc
             path: queues.mqsc

I get the below errors when i try to create the deployment:

2020-06-11T15:23:02.679Z CPU architecture: amd64
2020-06-11T15:23:02.680Z Linux kernel version: 4.4.156-94.64-default
2020-06-11T15:23:02.680Z Container runtime: kube
2020-06-11T15:23:02.680Z Base image: Red Hat Enterprise Linux 8.1 (Ootpa)
2020-06-11T15:23:02.685Z Running as user ID 888 () with primary group 888, and supplementary groups 0
2020-06-11T15:23:02.686Z Capabilities (bounding set): chown,dac_override,fowner,fsetid,kill,setgid,setuid,setpcap,net_bind_service,net_raw,sys_chroot,mknod,audit_write,setfcap
2020-06-11T15:23:02.686Z seccomp enforcing mode: disabled
2020-06-11T15:23:02.686Z Process security attributes: cri-containerd.apparmor.d (enforce)
2020-06-11T15:23:02.687Z No volume detected. Persistent messages may be lost
2020-06-11T15:23:02.716Z Set password for "admin" user
2020-06-11T15:23:02.731Z Using queue manager name: TEST1
2020-06-11T15:23:02.743Z Created directory structure under /var/mqm
2020-06-11T15:23:02.743Z Image created: 2019-12-05T18:39:02+00:00
2020-06-11T15:23:02.743Z Image tag: ibm-mqadvanced-server-dev:9.1.4.0-r1-amd64
2020-06-11T15:23:02.758Z MQ version: 9.1.4.0
2020-06-11T15:23:02.758Z MQ level: p914-L191127.DE
2020-06-11T15:23:02.758Z MQ license: Developer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7e71a9]

goroutine 1 [running]:
github.com/ibm-messaging/mq-container/vendor/software.sslmate.com/src/go-pkcs12.Encode(0x9f05c0, 0xc00008e5a0, 0x8f3aa0, 0xc000118b60, 0x0, 0xc000098110, 0x1, 0x1, 0xc000028350, 0xc, ...)
        /opt/app-root/src/go/src/github.com/ibm-messaging/mq-container/vendor/software.sslmate.com/src/go-pkcs12/pkcs12.go:409 +0xd9
github.com/ibm-messaging/mq-container/internal/tls.processKeys(0x94e329, 0x11, 0x95051e, 0x15, 0xc00019fab0, 0xc00019fa50, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/app-root/src/go/src/github.com/ibm-messaging/mq-container/internal/tls/tls.go:253 +0x4e6
github.com/ibm-messaging/mq-container/internal/tls.ConfigureTLSKeystores(0x94e329, 0x11, 0x94eaaf, 0x12, 0x95051e, 0x15, 0xc00009482d, 0x540, 0x0, 0x0, ...)
        /opt/app-root/src/go/src/github.com/ibm-messaging/mq-container/internal/tls/tls.go:447 +0x2b5
main.doMain(0x0, 0x0)
        /opt/app-root/src/go/src/github.com/ibm-messaging/mq-container/cmd/runmqserver/main.go:130 +0xa9a
main.main()
        /opt/app-root/src/go/src/github.com/ibm-messaging/mq-container/cmd/runmqserver/main.go:226 +0x22

The above are the logs of the POD, captured when the status is 'Error' (kubectl get pods -n dev-ns)

Note that if i do not supply the TLS certificates, that is, i do not define the mounts and volumes specific to the TLS certificates and key, the deployment occurs correctly without any issues. 

Could you please suggest as to what might be causing this, and a resolution (if this is something that i need to consider at my end)?

**Comment by OmBabosa** [comment]
This is resolved. A further analysis suggested that the private key and certificate should be named the same. If you see the volumes that i have mentioned above, they name as follows:

- key: privatekey
path: test1key.key
- key: personalcert
path: test1.crt

That private key and personal certificate should have been created with same names as below:
- key: privatekey
path: test1key
- key: personalcert
path: test1.crt
