### ISSUE TITLE
OKD 4 authentication failed

### ISSUE THREAD

**Issue by cdprete** [ibm-messaging/mq-container#455]
Hi.
I've a "custom" Docker image which simply copies a config file in the container for creating some queues and disabling the authentication like the following: 
```
FROM ibmcom/mq
ENV HOME /root
COPY config.mqsc /etc/mqm/
```

and, in the `config.mqsc`:
```
DEFINE CHANNEL(PASSWORD.SVRCONN) CHLTYPE(SVRCONN)
SET CHLAUTH(PASSWORD.SVRCONN) TYPE(BLOCKUSER) USERLIST('nobody') DESCR('Allow privileged users on this channel')
SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS) DESCR('BackStop rule')
SET CHLAUTH(PASSWORD.SVRCONN) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
REFRESH SECURITY TYPE(CONNAUTH)

DEFINE QLOCAL(MYQUEUE.IN ) DEFPSIST(YES) MAXDEPTH(500000)
DEFINE QLOCAL(MYQUEUE.OUT ) DEFPSIST(YES) MAXDEPTH(500000)

DEFINE QLOCAL(CS.ERROR) DEFPSIST(YES) MAXDEPTH(500000)

ALTER QMGR CHLAUTH(DISABLED) CONNAUTH(' ')
ALTER CHANNEL('SYSTEM.DEF.SVRCONN') CHLTYPE(SVRCONN) MCAUSER('mqm')
REFRESH SECURITY TYPE(CONNAUTH)
```

The problem is that if I run this image within Openshift 3 (or Docker or k8s in docker-desktop), the queues are created under the user `mqm` and I can connect to it from my Java application by using `mqm` as user and an empty password.
If I deploy the exact same image on Openshift 4, the queues are created under the user `1001` (or a random one) and the authentication fails if I try to connect to them from the Java application, since it expects `mqm` as user (as well as in the `config.mqsc`).

The process running on Openshift 4 looks like 
```
1001         259  0.2  0.2 2307280 45788 ?       Ssl  06:56   0:00 /opt/mqm/bin/amqzxma0 -m QM1 -x -u 1001
```
but in the Openshift 3 it looks like
```
1000100+    152  0.0  0.0 2324200 33812 ?       Ssl  May03   0:06 /opt/mqm/bin/amqzxma0 -m QM1 -x -u mqm
```

Stacktrace produced by the application:
```
Caused by: org.springframework.jms.JmsSecurityException: JMSWMQ2013: The security authentication was not valid that was supplied for QueueManager 'QM1' with connection mode 'Client' and host name 'my-mq(1414)'.; nested exception is com.ibm.msg.client.jms.DetailedJMSSecurityException: JMSWMQ2013: The security authentication was not valid that was supplied for QueueManager 'QM1' with connection mode 'Client' and host name 'my-mq(1414)'.
Please check if the supplied username and password are correct on the QueueManager to which you are connecting.; nested exception is com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').
		at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:286)
		at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:185)
		at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:507)
		at org.springframework.jms.core.JmsTemplate.browseSelected(JmsTemplate.java:1029)
		at org.springframework.jms.core.JmsTemplate.browse(JmsTemplate.java:991)
		... 78 more
	Caused by: com.ibm.msg.client.jms.DetailedJMSSecurityException: JMSWMQ2013: The security authentication was not valid that was supplied for QueueManager 'QM1' with connection mode 'Client' and host name 'my-mq(1414)'.
Please check if the supplied username and password are correct on the QueueManager to which you are connecting.
		at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:531)
		at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
		at com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:424)
		at com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)
		at com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)
		at com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)
		at com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createConnection(JmsConnectionFactoryImpl.java:236)
		at com.ibm.mq.jms.MQConnectionFactory.createCommonConnection(MQConnectionFactory.java:6016)
		at com.ibm.mq.jms.MQQueueConnectionFactory.createQueueConnection(MQQueueConnectionFactory.java:111)
		at com.ibm.mq.jms.MQQueueConnectionFactory.createConnection(MQQueueConnectionFactory.java:187)
		at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:196)
		at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:494)
		... 80 more
	Caused by: com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2035' ('MQRC_NOT_AUTHORIZED').
		at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
		... 90 more
```

Any idea what the issue could be?

**Comment by arthurbarr** [comment]
The difference between OpenShift Container Platform (OCP) 3 and 4 is really a difference in configuration in the clusters you are using.  OCP has the concept of `SecurityContextConstraints` (SCC) which limit the `securityContext` you can use in your Pods.  In both OCP 3 and 4, the default SCC is `restricted`, which means containers must be run with a security context that uses a random (nont-root) UID in the container, must have SELinux enabled, and (usually) can't use privilege escalation.

In order to support this more secure way of running, in MQ 9.1.5, we moved away from using the `mqm` user anywhere in containers, by adopting a new "no-install" version of MQ, which doesn't use RPMs.  With the "no-install" version, MQ runs with whatever UID starts the queue manager.  The RPM version of MQ requires privilege escalation (the `setuid` bit is set to run certain commands as the root user, to check OS passwords), so as part of moving to a more secure system, we've removed this.  The net effect is that you can't use OS users inside the container any more.  Instead we recommend either using LDAP or mutual TLS.

MQ Advanced for Developers is a special case, as the default developer configuration has two users: "admin" and "app".  To continue to enable those users, we created a custom MQ auth service, which still allows just those two special users.  The custom service is based on an HTPasswd file, so can theoretically be extended to other users too, but that's not something we've tested thoroughly.

**Comment by cdprete** [comment]
Hi @arthurbarr.
Thanks for the reply.

I see your points and I've read about the SCC&Co but even using the MQ version 9.2.2.0, in OKD 3 it was still working fine (so with `mqm` by magic), but for OKD 4 this is not the case. <br/>
What I've also found out is that starting from Openshift 4.3 (I'm running on OKD 4.5), the user having the "random" UID is also created in the `passwd` file and this seems to be the cause of the issue.

In OKD 3 the container runs also with a "random" UID, but the processes like `amqzxma0 -m QM1 -x -u mqm` were still having the `mqm` value for the `-u` option and, as a result, all the created queues as well as other files were belonging to `mqm`.

**Comment by arthurbarr** [comment]
The MQ version 9.2.2.0 container does not have an `mqm` user defined in the Linux "OS" (libraries).  Internally, MQ still might pass around the `mqm` string to mean "the user which started the queue manager", so I don't think we need to worry about what the `-u` option says.

Regardless of what behaviour you're seeing with OpenShift 3, the behaviour on OpenShift 4 is this: the MQ containers (from MQ 9.1.5 onwards) **do not contain** an `mqm` user.  These versions will run as **any** UID which the container is run with, but that user must be part of the `root` group (GID 0).  This is the default behaviour with the `restricted` SCC in OpenShift 4, and that SCC is the default.  If you want to connect an application using a user ID and password, then you have the following options:

* If you are using the (unwarranted) MQ Advanced for Developers image, then there are two users pre-created for you called `app` and `admin`, with some permissions set up.  These are created in the underlying container using a custom auth service with MQ, and not the OS libraries.
* You can configure LDAP authentication, and use a user defined in the LDAP directory

I hope this helps.

**Comment by cdprete** [comment]
Hi.
In the end I ended up using the `app` user.
Thanks for the clarifications. :)
